export const filters = ['all', 'active', 'completed'] as const;

export const placeholderTasks = [
  'Read a book',
  'Work on personal project',
  'Go for a walk',
  'Learn a new language',
  'Try a new recipe',
  'Exercise',
  'Listen to a podcast',
  'Watch a movie',
  'Practice coding challenges',
  'Write in a journal',
  'Call a friend',
  'Attend a workshop',
  'Visit a museum',
  'Go for a run',
  'Take a nap',
  'Volunteer for a cause',
  'Explore a new neighborhood',
  'Plan your next vacation',
  'Do a puzzle',
  'Learn to play a musical instrument',
  "Visit a farmer's market",
  'Join a book club',
  'Attend a concert',
  'Try a new hobby',
  'Take a cooking class',
  'Practice meditation',
  'Go camping',
  'Visit a botanical garden',
  'Create a playlist',
  'Take a yoga class',
  'Do a digital detox',
  'Join a sports team',
  'Learn about a new topic online',
  'Attend a fitness class',
  'Explore a nearby park',
  'Attend a webinar',
  'Try a new workout routine',
  'Join a hiking group',
  'Write poetry',
  'Visit a historical site',
  'Attend a meetup',
  'Take a photography tour',
  'Explore a nearby beach or lake',
  'Join a community garden',
  'Go to a food festival',
  'Host a game night',
  'Join a club or organization',
  'Take a pottery class',
  'Try a new restaurant',
  'Visit an art gallery',
  'Try a new coffee shop',
  'Go stargazing',
  'Attend a comedy show',
  'Do a home improvement project',
  'Take a bike ride',
  'Go to a street fair',
  'Join a community clean-up event',
  'Take a dance class',
  'Host a DIY craft night',
  'Take a painting class',
  'Attend a poetry reading',
  'Try a new type of tea',
];
